<a href="https://colab.research.google.com/github/Alexy1980/deep_learning/blob/main/test_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install terra_ai

     |████████████████████████████████| 81kB 3.7MB/s 


In [1]:
import numpy as np

In [6]:
arr = np.array([[a*a+b*b for a in range(15)] for b in range(15)])
print(arr)

[[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196]
 [  1   2   5  10  17  26  37  50  65  82 101 122 145 170 197]
 [  4   5   8  13  20  29  40  53  68  85 104 125 148 173 200]
 [  9  10  13  18  25  34  45  58  73  90 109 130 153 178 205]
 [ 16  17  20  25  32  41  52  65  80  97 116 137 160 185 212]
 [ 25  26  29  34  41  50  61  74  89 106 125 146 169 194 221]
 [ 36  37  40  45  52  61  72  85 100 117 136 157 180 205 232]
 [ 49  50  53  58  65  74  85  98 113 130 149 170 193 218 245]
 [ 64  65  68  73  80  89 100 113 128 145 164 185 208 233 260]
 [ 81  82  85  90  97 106 117 130 145 162 181 202 225 250 277]
 [100 101 104 109 116 125 136 149 164 181 200 221 244 269 296]
 [121 122 125 130 137 146 157 170 185 202 221 242 265 290 317]
 [144 145 148 153 160 169 180 193 208 225 244 265 288 313 340]
 [169 170 173 178 185 194 205 218 233 250 269 290 313 338 365]
 [196 197 200 205 212 221 232 245 260 277 296 317 340 365 392]]
